### PR TITLE
Improved composer support

### PR DESCRIPTION
**Pull request by Mte90**
In that way works very better with composer when are used tools that require autoloading without wordpress.

### CODE REVIEW

**Comment by Mte90** [comment]
any updates for this pr?

**Comment by julien731** [comment]
Sorry for the delay @Mte90 I'll try to take care of this one over the weekend.

**Comment by Mte90** [comment]
any updates? I use review-me but download also the original version that is not working...

**Comment by julien731** [comment]
Sorry about the delay @Mte90 I'm merging now.

**Comment by Mte90** [comment]
it is possible to do a new release on review-me and this repo?

**Comment by Mte90** [comment]
waiting for the packages because I am still using my forked version or I cannot resolve rightly the dependences.

**Comment by julien731** [comment]
I just pushed a new release @Mte90

**Comment by Mte90** [comment]
Perfect, miss only review-me but I can use the develop branch.

**Pull request merged**
